pipeline {
    agent any
    environment {
        POSTGRES_SECRET_USR = credentials('jenkins-postgres-username')
        POSTGRES_SECRET_PSW = credentials('jenkins-postgres-password')
    }
    stages {
        stage('Update Packages') {
            steps {
                sh 'apt-get update'
                sh 'apt-get install -y libpq-dev'
            }
        }
        stage('Install Python') {
            steps {
                sh 'apt-get install -y python3 python3-pip python3-venv'
            }
        }
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/viri77/dqe-automation.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r PyTest DQ Framework/requirements.txt
                '''
            }
        }
        stage('Run PyTest') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest tests -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user=$POSTGRES_SECRET_USR \
                        --db_password=$POSTGRES_SECRET_PSW \
                        --html=html_report/report.html
                '''
            }
        }
        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true
                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'html_report',
                    reportFiles: 'report.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}