pipeline {
    agent any

    environment {
        POSTGRES_SECRET_USR = credentials('jenkins-postgres-username')
        POSTGRES_SECRET_PSW = credentials('jenkins-postgres-password')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Setup Python venv') {
            steps {
                sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }
        stage('Run PyTest') {
            steps {
                sh '''
                    . venv/bin/activate
                    pytest tests -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user=$POSTGRES_SECRET_USR \
                        --db_password=$POSTGRES_SECRET_PSW \
                        --html=html_report/report.html
                '''
            }
        }
        stage('Archive Test Report') {
            steps {
                archiveArtifacts artifacts: 'html_report/**', allowEmptyArchive: true

                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'html_report',
                    reportFiles: 'report.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
}