pipeline {
    agent any

    environment {
        // Получаем секреты из Jenkins Credentials Store
        POSTGRES_SECRET_USR = credentials('jenkins-postgres-username')
        POSTGRES_SECRET_PSW = credentials('jenkins-postgres-password')
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Run PyTest') {
            steps {
                sh '''
                    pytest tests -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user=$POSTGRES_SECRET_USR \
                        --db_password=$POSTGRES_SECRET_PSW \
                        --html=html_report/report.html
                '''
            }
        }
        stage('Archive Test Report') {
            steps {
                // Архивируем всю папку html_report (включая assets)
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

                // Публикуем HTML-отчёт
                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'PyTest DQ Framework/html_report',
                    reportFiles: 'report.html', // или 'index.html', если переименовали
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }
}